nelmio_api_doc:
    documentation:
        info:
            title: Backend API
            description: Available API endpoints on this service
            version: 0.0.1
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
            - ^/bporg
